# Persistent Volume Claim for Opal
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Opal Deployment and Service
apiVersion: v1
kind: Service
metadata:
  name: opal
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: opal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opal
  template:
    metadata:
      labels:
        app: opal
    spec:
      serviceAccountName: rock-spawner-service-account
      containers:
        - name: opal
          image: obiba/opal:snapshot
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGODATA_DATABASE
              value: "opal"
            - name: MONGO_USER
              value: "root"
            - name: MONGO_PASSWORD
              value: "example"
            - name: ROCK_HOSTS
              value: ""
          volumeMounts:
            - name: opal-storage
              mountPath: /srv
      volumes:
        - name: opal-storage
          persistentVolumeClaim:
            claimName: opal-pvc
