# Rock (R Server) Deployment and Service
apiVersion: v1
kind: Service
metadata:
  name: rock
spec:
  ports:
    - port: 8085
  selector:
    app: rock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rock
  template:
    metadata:
      labels:
        app: rock
    spec:
      containers:
        - name: rock
          image: obiba/rock:latest
          ports:
            - containerPort: 8085
